-- ============================================================================
-- CLEANUP DUMMY DATA SCRIPT
-- ============================================================================
-- Purpose: Remove all dummy data generated by generate_dummy_data.sql
-- Safe to run multiple times (idempotent)
-- ============================================================================

BEGIN;

-- Delete in reverse order of foreign key dependencies

-- 1. Delete dummy events
DELETE FROM events WHERE metadata->>'dummy' = 'true';

-- 2. Delete dummy cart_items
DELETE FROM cart_items 
WHERE cart_id IN (
    SELECT cart_id FROM carts 
    WHERE user_id IN (SELECT user_id FROM users WHERE email LIKE 'DUMMY%')
);

-- 3. Delete dummy carts
DELETE FROM carts 
WHERE user_id IN (SELECT user_id FROM users WHERE email LIKE 'DUMMY%');

-- 4. Delete dummy shipments
DELETE FROM shipments WHERE tracking_number LIKE 'DUMMY%';

-- 5. Delete dummy product_reviews
DELETE FROM product_reviews WHERE review_text LIKE 'DUMMY%';

-- 6. Delete dummy payments
DELETE FROM payments WHERE transaction_id LIKE 'DUMMY%';

-- 7. Delete dummy order_items
DELETE FROM order_items 
WHERE order_id IN (
    SELECT order_id FROM orders WHERE shipping_address LIKE 'DUMMY%'
);

-- 8. Delete dummy orders
DELETE FROM orders WHERE shipping_address LIKE 'DUMMY%';

-- 9. Delete dummy inventory
DELETE FROM inventory WHERE warehouse_location LIKE 'DUMMY%';

-- 10. Delete dummy coupons
DELETE FROM coupons WHERE code LIKE 'DUMMY%';

-- 11. Delete dummy products
DELETE FROM products WHERE sku LIKE 'DUMMY%';

-- 12. Delete dummy categories
DELETE FROM categories WHERE name LIKE 'DUMMY%';

-- 13. Delete dummy users
DELETE FROM users WHERE email LIKE 'DUMMY%';

-- Verify cleanup
DO $$
DECLARE
    v_users INTEGER;
    v_categories INTEGER;
    v_products INTEGER;
    v_orders INTEGER;
    v_order_items INTEGER;
    v_payments INTEGER;
    v_shipments INTEGER;
    v_reviews INTEGER;
    v_carts INTEGER;
    v_cart_items INTEGER;
    v_inventory INTEGER;
    v_coupons INTEGER;
    v_events INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_users FROM users WHERE email LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_categories FROM categories WHERE name LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_products FROM products WHERE sku LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_orders FROM orders WHERE shipping_address LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_order_items FROM order_items WHERE order_id IN (SELECT order_id FROM orders WHERE shipping_address LIKE 'DUMMY%');
    SELECT COUNT(*) INTO v_payments FROM payments WHERE transaction_id LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_shipments FROM shipments WHERE tracking_number LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_reviews FROM product_reviews WHERE review_text LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_carts FROM carts WHERE user_id IN (SELECT user_id FROM users WHERE email LIKE 'DUMMY%');
    SELECT COUNT(*) INTO v_cart_items FROM cart_items WHERE cart_id IN (SELECT cart_id FROM carts WHERE user_id IN (SELECT user_id FROM users WHERE email LIKE 'DUMMY%'));
    SELECT COUNT(*) INTO v_inventory FROM inventory WHERE warehouse_location LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_coupons FROM coupons WHERE code LIKE 'DUMMY%';
    SELECT COUNT(*) INTO v_events FROM events WHERE metadata->>'dummy' = 'true';
    
    RAISE NOTICE 'DUMMY DATA CLEANUP COMPLETE:';
    RAISE NOTICE '  Users remaining: % (should be 0)', v_users;
    RAISE NOTICE '  Categories remaining: % (should be 0)', v_categories;
    RAISE NOTICE '  Products remaining: % (should be 0)', v_products;
    RAISE NOTICE '  Orders remaining: % (should be 0)', v_orders;
    RAISE NOTICE '  Order Items remaining: % (should be 0)', v_order_items;
    RAISE NOTICE '  Payments remaining: % (should be 0)', v_payments;
    RAISE NOTICE '  Shipments remaining: % (should be 0)', v_shipments;
    RAISE NOTICE '  Reviews remaining: % (should be 0)', v_reviews;
    RAISE NOTICE '  Carts remaining: % (should be 0)', v_carts;
    RAISE NOTICE '  Cart Items remaining: % (should be 0)', v_cart_items;
    RAISE NOTICE '  Inventory remaining: % (should be 0)', v_inventory;
    RAISE NOTICE '  Coupons remaining: % (should be 0)', v_coupons;
    RAISE NOTICE '  Events remaining: % (should be 0)', v_events;
    
    IF v_users = 0 AND v_categories = 0 AND v_products = 0 AND v_orders = 0 
       AND v_order_items = 0 AND v_payments = 0 AND v_shipments = 0 
       AND v_reviews = 0 AND v_carts = 0 AND v_cart_items = 0 
       AND v_inventory = 0 AND v_coupons = 0 AND v_events = 0 THEN
        RAISE NOTICE '✅ All dummy data successfully removed!';
    ELSE
        RAISE WARNING '⚠️ Some dummy data still remains. Check the counts above.';
    END IF;
END $$;

COMMIT;
